#config_version=5

show_player:
  mode_attract_started: 
    attract_display_loop:
      loops: -1
      speed: 1
    blueFlicker:
      loops: -1
      speed: 1
      show_tokens:
        led: l_testled
  
