#config_version=5
game:
  balls_per_game: 10

playfields:
  playfield0:
    label: Playfield 0
    tags: default
    default_source_device: bd_plunger_p0
  # playfield1:
  #     label: Playfield 1
  #     default_source_device: None

hardware:
  platform: p3_roc
  driverboards: pdb
  stepper_controllers: trinamics_steprocker

trinamics_steprocker:
  port: /dev/ttyACM0

light_settings:
  default_fade_ms: 40

displays:
  window:
    width: 800
    height: 600

slides:
  welcome_slide:
    widgets:
      - type: text
        text: Forbidden Island!
        font_size: 50
        color: red
      - type: rectangle
        width: 400
        height: 60

slide_player:
  init_done: welcome_slide

queue_relay_player:
  machine_reset_phase_3:
    post: "waiting_on_stepper"
    wait_for: "stepper_center_turret_ready"

config:
  - hardware.yaml
  - torchshows.yaml

modes:
  - base
#  - centermode1

keyboard:
    s:
      switch: s_start
#    p:
#      switch: s_p0launch




