#config_version=5

steppers:
    center_turret:
        number: 0
        debug: true     
        mode: position
        pos_max: 1.0
        pos_min: -1.0
        move_current:  32 #percent
        hold_current:   8 #percent
        homing_direction: clockwise #when facing the shaft
        homing_speed: 0.2 #user units/sec
        microstep_per_fullstep: 16 # 1/16 mode (1 step = 1/16 of a full step)
        fullstep_per_userunit: 1400 # UU=1 Revolution = 200 full steps per rev (1.8 deg stepper) * 7 gear ratio
        velocity_limit: 0.5 #user units/sec   (so, 0.8 RPS of output gear )
        acceleration_limit: 2.0 #user units/sec^2  (so, 2 RPS^S of output gear)
        reset_position: 0.45
        #reset_position: 0
        reset_events: machine_reset_phase_3
        named_positions:
              -0.05: goto_playfield1_sdtm
              0.45: goto_playfield0_sdtm

#--------------------------------------------------------------------------
#  SWITCHES
#  p3_roc Switche number - SW-16 Board(0-15)/Bank(A=0,B=1)/Switch num(0-7)
#--------------------------------------------------------------------------
switches:
  # --- Playfield 0 ---
  s_flipper_left_EOS_p0:    #gray
    number: 2/0/1
  s_flipper_right_EOS_p0:   #orange
    number: 2/0/0
  s_flipper_right_button_p0:  #yellow
    number: 0/1/0
  s_flipper_left_button_p0: #brown
    number: 0/1/2
  s_right_sling_p0:
    number: 2/0/2
    tags: playfield0_active
  s_left_sling_p0:
    number: 2/0/4
    tags: playfield0_active
  s_right_outlane_p0:
    number: 2/0/6
    tags: playfield0_active
  s_right_inlane_p0:
    number: 2/1/0
    tags: playfield0_active
  s_left_outlane_p0:
    number: 2/0/3
    tags: playfield0_active
  s_left_inlane_p0:
    number: 2/0/7
    tags: playfield0_active
  s_plunger_p0:
    number: 2/0/5
  s_trough_jam_p0:
    number: 3/1/7
    type: nc
  s_trough_ball1_p0:
    number: 3/1/0
    type: nc
  s_trough_ball2_p0:
    number: 3/0/0
  s_trough_ball3_p0:
    number: 3/1/1  
  s_trough_ball4_p0:
    number: 3/1/2  
  s_trough_ball5_p0:
    number: 3/1/3  
  s_trough_ball6_p0:
    number: 3/1/4  
  s_trough_ball7_p0:
    number: 3/1/5
  s_trough_ball8_p0:
    number: 3/1/6


  # --- Playfield 1 ---
  # s_flipper_right_EOS_p1:    #gray (didn't mirror P0)
  #   number: 0/0/0
  # s_flipper_left_EOS_p1:   #orange 
  #   number: 0/0/1
  # s_flipper_right_button_p1:  #yellow
  #   number: 0/0/6
  # s_flipper_left_button_p1: #brown
  #   number: 0/0/7    

  # --- Center Mechanism ---
  #  |----> Ball trough ---
  s_cmbt_ball1: # purple
    number: 1/0/4
    type: nc
  s_cmbt_ball2: # orange
    number: 1/1/7
  s_cmbt_ball3: # yellow
    number: 1/1/1
  s_cmbt_ball4: # brown
    number: 1/1/2
  s_cmbt_ball5: # grey
    number: 1/1/3
  s_cmbt_ball6: # red
    number: 1/1/4
  s_cmbt_ball7: # purple
    number: 1/1/5
  s_cmbt_ball8: # teal
    number: 1/1/6
  s_cmbt_jam:
    number: 1/0/0  # orange
    type: nc
  #   |----> subway entrances ---
  s_cmbt_entrance_p1:
    number: 1/0/2  # orange (again for some reason)
    type: nc
  s_cmbt_entrance_p0:
    number: 1/0/3  # red
    type: nc

  # misc
  s_start:
    number: 1/1/0
    tags: start
  s_launch_p0:
    number: 1/0/1

#--------------------------------------------------------------------------
#  COILS
# p3_roc Coil number - Ax-By-Z  - x=BoardAddress, y=Bank(A=0,B=1),Ouput num(0-7)
# ex: A0-B1-6 = Address 0 board, Bank B, Output 6
#--------------------------------------------------------------------------
coils:
  # --- Playfield 0 ----
  c_flipper_right_power_p0: #yellow
    number: A0-B0-0
    default_pulse_ms: 25
    allow_enable: false
    default_hold_power: 0.125
  c_flipper_right_hold_p0:  #white
    number: A0-B0-1
    allow_enable: true # Hold coil allowed to stay on
    default_hold_power: 0.5
  c_flipper_left_power_p0:  #blue
    number: A0-B0-2
    default_pulse_ms: 25
    allow_enable: false
    default_hold_power: 0.125
  c_flipper_left_hold_p0:   #teal
    number: A0-B0-3
    allow_enable: true # Hold coil allowed to stay on
    default_hold_power: 0.5
  c_left_sling_p0: #red
    number: A0-B0-4
    default_pulse_ms: 10
    allow_enable: false
    default_hold_power: 0.125
  c_right_sling_p0: # yellow
    number: A0-B0-5
    default_pulse_ms: 10
    allow_enable: false
    default_hold_power: 0.125
  c_trough_p0: # white
    number: A0-B0-6
    default_pulse_ms: 14
    allow_enable: false
    default_hold_power: 0.125
  c_plunger_p0: #blue
    number: A0-B0-7
    default_pulse_ms: 13
    allow_enable: false
    default_hold_power: 0.125
    
  # --- Playfield 1 ---
  c_flipper_left_power_p1: #yellow
    number: A0-B1-0
    default_pulse_ms: 20
    allow_enable: false
    default_hold_power: 0.125
  c_flipper_left_hold_p1:  #white
    number: A0-B1-1
    allow_enable: true # Hold coil allowed to stay on
    default_hold_power: 1.0
  c_flipper_right_power_p1:  #blue
    number: A0-B1-2
    allow_enable: false
    default_pulse_ms: 20
    default_hold_power: 0.125
  c_flipper_right_hold_p1:   #teal
    number: A0-B1-3
    allow_enable: true # Hold coil allowed to stay on
    default_hold_power: 1.0

  # --- Center Mech ----
  c_cmbt_eject:   # blue
    number: A0-B1-4
    allow_enable: false
    default_pulse_ms: 20

#--------------------------------------------------------------------------
#  LEDS
#--------------------------------------------------------------------------
lights:
  l_testled:
    type: rgb
    subtype: led
    number: 8-0-1-2
#    default_on_color: ff0000
    fade_ms: 150
    platform_settings:
      polarity: True    

#light_player:
#  machine_reset_phase_3:
#    l_testled: ff0000

#--------------------------------------------------------------------------
#  FLIPPERS
#--------------------------------------------------------------------------
flippers:
    # Playfield 0
    left_flipper_p0:
        main_coil: c_flipper_left_power_p0
        hold_coil: c_flipper_left_hold_p0
        activation_switch: s_flipper_left_button_p0
        eos_switch: s_flipper_left_EOS_p0
        #enable_events: machine_reset_phase_3 # temp - this allows flipper to work at boot
        use_eos: true
        playfield: playfield0

    right_flipper_p0:
        main_coil: c_flipper_right_power_p0
        hold_coil: c_flipper_right_hold_p0
        activation_switch: s_flipper_right_button_p0
        eos_switch: s_flipper_right_EOS_p0
        #enable_events: machine_reset_phase_3 # temp - this allows flipper to work at boot
        use_eos: true
        playfield: playfield0

    # # Playfield 1
    # left_flipper_p1:
    #     main_coil: c_flipper_left_power_p1
    #     hold_coil: c_flipper_left_hold_p1
    #     activation_switch: s_flipper_left_button_p1
    #     eos_switch: s_flipper_left_EOS_p1
    #     enable_events: machine_reset_phase_3 # temp - this allows flipper to work at boot
    #     use_eos: true
    #     playfield: playfield
        
    # right_flipper_p1:
    #     main_coil: c_flipper_right_power_p1
    #     hold_coil: c_flipper_right_hold_p1
    #     activation_switch: s_flipper_right_button_p1
    #     eos_switch: s_flipper_right_EOS_p1
    #     enable_events: machine_reset_phase_3 # temp - this allows flipper to work at boot
    #     use_eos: true
    #     playfield: playfield

#------------------------------------------------------------------------------------------
# Auto Fire Coils
#------------------------------------------------------------------------------------------

autofire_coils:
    left_sling_p0:
      coil: c_left_sling_p0
      switch: s_left_sling_p0
      playfield: playfield0
    right_sling_p0:
      coil: c_right_sling_p0
      switch: s_right_sling_p0
      playfield: playfield0
 
 #-----------------------------------------------------------------------------------------
 # Ball Devices
 # ----------------------------------------------------------------------------------------
ball_devices:
    bd_centrtrough:
        ball_switches: s_cmbt_ball1,s_cmbt_ball2,s_cmbt_ball3,s_cmbt_ball4,s_cmbt_ball5,s_cmbt_ball6,s_cmbt_ball7,s_cmbt_ball8,s_cmbt_jam
        eject_coil: c_cmbt_eject
        jam_switch: s_cmbt_jam
        eject_coil_jam_pulse: 15ms
        eject_targets: playfield0
        captures_from: playfield0
        ball_missing_target: playfield0
        eject_timeouts: 500ms

    bd_trough_p0:
        ball_switches: s_trough_ball1_p0,s_trough_ball2_p0,s_trough_ball3_p0,s_trough_ball4_p0,s_trough_ball5_p0,s_trough_ball6_p0,s_trough_ball7_p0,s_trough_ball8_p0,s_trough_jam_p0
        eject_coil: c_trough_p0
        tags: trough,home,drain
        jam_switch: s_trough_jam_p0
        eject_coil_jam_pulse: 15ms
        eject_targets: bd_plunger_p0
        captures_from: playfield0
        ball_missing_target: playfield0

    bd_plunger_p0:
        ball_switches: s_plunger_p0
        eject_coil: c_plunger_p0
        eject_timeouts: 3s
        eject_targets: playfield0
        ball_missing_target: playfield0
        captures_from: playfield0

#     #dummy:
#     #    tags: ball_add_live
#     #    mechanical_eject: true